version: '3'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: paygo
    volumes:
      - paygo-db:/var/lib/postgresql/data

volumes:
  gerentu:
  paygo-db:
