import { AuthProvider } from '@front/auth/context';
import { SnackbarProvider } from '@front/components/snackbar';
import ThemeProvider from '@front/theme';

export const metadata = {
  title: 'Welcome to apps/front',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ThemeProvider>
            <SnackbarProvider>
              {children}
            </SnackbarProvider>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
